# WordPress Strict Security Configuration
# Comprehensive security rules for thorough security audits
# Includes all security rules with maximum coverage

include:
  - packs/wp-core-security/
  - packs/wp-core-quality/
  - packs/experimental/

# Performance optimization settings
exclude:
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/*.min.js"
  - "**/*.min.css"

# Enable all rule categories
rule-filters:
  - include: "wordpress.security.*"
  - include: "wordpress.quality.*"
  - include: "wordpress.performance.*"
